### ISSUE TITLE
Not Retriving all data using this gem

### ISSUE THREAD

**Issue by pratap477** [knrz/Quandl-Ruby#7]
Using quandl_ruby gem is not retrive all quandle data,  if without use quandl_gem and call quandal api using rest_clinet then all data will be retrived..

Any default limit set for retriving quandl apii data.

**Comment by knrz** [comment]
No limit that I know of. Can you provide an example?

**Comment by schopenhauer** [comment]
Same problems happened to me. I believe the URI should be updated to:_

 API_URI = 'https://www.quandl.com/api/v1'

instead of 

 API_URI = 'https://www.quandl.com/api/'

**Comment by schopenhauer** [comment]
The example below returns an empty array:
```ruby
@results = Quandl::Search.get('crude oil')
#<Quandl::Search:0x007fd03530e618> 
```

**Comment by knrz** [comment]
Quandl's removed searching functionality from their API :disappointed:
